name: ElevatED
description: "Learning Platform Enhanced By AI"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # API - Data - Cache
  shared_preferences:
  sqflite:
  ftpconnect: ^2.0.7
  dio:
  # State Managment - Dependency Injection
  flutter_bloc:
  equatable:
  get_it:
  # localization - notifications - theme - adaptiveness
  flutter_local_notifications: ^18.0.1
  flutter_screenutil:
  easy_localization:
  themed: ^8.1.0
  # images & files
  cached_network_image:
  path_provider: ^2.1.5
  file_picker: ^10.0.0
  image_cropper:
  image_picker:
  flutter_svg:
  lottie:
  image:
  path:
  # Firebase
  firebase_crashlytics:
  firebase_messaging:
  firebase_analytics:
  firebase_core:
  # UI
  flutter_lazy_indexed_stack: ^0.0.6
  grouped_list: ^6.0.0
  water_drop_nav_bar:
  cupertino_icons:
  video_player: ^2.8.2
  fl_chart:
  pinput:
  # Security
  flutter_dotenv: ^5.2.1
  # General
  flutter_launcher_icons:
  flutter_native_splash:
  url_launcher:
  app_links: ^6.4.0
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/splash_logo.png
    - assets/images/
    - assets/translations/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: IcoMoon
      fonts:
        - asset: assets/fonts/icons/icomoon.ttf

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
          style: italic
          weight: 900
