// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGe9pgP-im1Zmd8l0UoVkDCdQARbQF3I',
    appId: '1:421398615191:web:9a30f8b631912da75585d2',
    messagingSenderId: '421398615191',
    projectId: 'elevated-a742a',
    authDomain: 'elevated-a742a.firebaseapp.com',
    storageBucket: 'elevated-a742a.firebasestorage.app',
    measurementId: 'G-DYC6Z36DY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCig3cIoi2wOXwZL67YEAlRrvrdLo_-F84',
    appId: '1:421398615191:android:5dd8a382f544abc55585d2',
    messagingSenderId: '421398615191',
    projectId: 'elevated-a742a',
    storageBucket: 'elevated-a742a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0agJjmjoeK21p5PRkzl1VodHUwYYqSb8',
    appId: '1:421398615191:ios:978d8139d9a8d5615585d2',
    messagingSenderId: '421398615191',
    projectId: 'elevated-a742a',
    storageBucket: 'elevated-a742a.firebasestorage.app',
    iosBundleId: 'com.example.eLearningAppGp',
  );
}
