enum UserRole { ADMIN, TEACHER, STUDENT }

enum Interests {
  WEB_DEV,
  MOBILE_DEV,
  GRAPHIC_DESIGN,
  MODELING_3D,
  OOP,
  FLUTTER
}

enum Themes { LIGHT, DARK }

enum Languages { ENGLISH, ARABIC }

enum KeyPrefs { IS_LOGGEDIN, EMAIL, PASSWORD, THEME, OLD_USER, IS_NOTIFICATON }
